#! /usr/bin/env python3

## INTRODUCTION AUX LISTES

#ex 1
alt = [300, 500, 600, 1000, 800, 900, 500, 600, 200, 0]
#b)
def altmax(l):
    max = l[0]
    for i in l:
        if i > max:
            max = i
    return max
#print(altmax(alt))

#c) #d)
def denivmax(l):
    deniv = l[1] - l[0]
    heure = 0
    for i in range(len(l)-1):
        heure += 1
        if l[i+1] - l[i] > deniv:
            deniv = l[i+1] - l[i]
            h = heure
    return h
#print(denivmax(alt))

#e)
def denivtotal(l):
    d = l[0]
    for i in range(len(l)-1):
        if l[i+1] - l[i] >= 0:
            d += l[i+1] - l[i]
    return d
#print(denivtotal(alt))

#f)
def sommets(l):
    s = []
    for i in range(1, len(l)-1):
        if l[i] > l[i-1] and l[i] > l[i+1]:
            s.append(l[i])
    return s
#print(sommets(alt))


#ex 2
l = [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0]
def bits(l):
    i = 0
    nmax = 0
    while i <= len(l):
        while l[i] != 0:
            i += 1
            if i == len(l):
                return nmax
        n = 0
        while l[i] == 0:
            n += 1
            i += 1
            if i == len(l):
                return nmax
        if n > nmax:
            nmax = n
        i += 1
    return nmax
#print(bits(l))

#ex 3
#a)
from numpy.random import randint
l = [randint(0, 99) for _ in range(99)]
#b)
